# Generated by Django 3.2.15 on 2023-12-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=16)),
                ('user_email', models.CharField(max_length=32)),
                ('user_password', models.CharField(max_length=16)),
                ('user_photo', models.CharField(max_length=16)),
            ],
        ),
    ]
